"""adsad

Revision ID: 60f3f34d57a0
Revises: 
Create Date: 2024-10-01 17:58:26.044037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f3f34d57a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack',
    sa.Column('id_attack', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('attack_bonus', sa.Integer(), nullable=False),
    sa.Column('damage_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_attack')
    )
    op.create_table('class',
    sa.Column('id_class', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_class')
    )
    op.create_table('equipment',
    sa.Column('id_equipment', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_equipment')
    )
    op.create_table('note',
    sa.Column('id_note', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id_note')
    )
    op.create_table('proficiency',
    sa.Column('id_proficiency', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proficiency', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_proficiency')
    )
    op.create_table('racial_group',
    sa.Column('id_racial_group', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('racial_group', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_racial_group')
    )
    op.create_table('user_type',
    sa.Column('id_user_type', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_user_type')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('id_user_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user_type'], ['user_type.id_user_type'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('character',
    sa.Column('id_character', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('constitution', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('initiative', sa.Integer(), nullable=False),
    sa.Column('health_current', sa.Integer(), nullable=False),
    sa.Column('health_max', sa.Integer(), nullable=False),
    sa.Column('proficiency_bonus', sa.Integer(), nullable=False),
    sa.Column('inspiration', sa.Integer(), nullable=False),
    sa.Column('id_attack', sa.Integer(), nullable=False),
    sa.Column('id_note', sa.Integer(), nullable=False),
    sa.Column('id_class', sa.Integer(), nullable=False),
    sa.Column('id_racial_group', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_attack'], ['attack.id_attack'], ),
    sa.ForeignKeyConstraint(['id_class'], ['class.id_class'], ),
    sa.ForeignKeyConstraint(['id_note'], ['note.id_note'], ),
    sa.ForeignKeyConstraint(['id_racial_group'], ['racial_group.id_racial_group'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_character')
    )
    op.create_table('character_equipment',
    sa.Column('id_ch_equipment', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checker', sa.Boolean(), nullable=False),
    sa.Column('id_equipment', sa.Integer(), nullable=False),
    sa.Column('id_character', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_character'], ['character.id_character'], ),
    sa.ForeignKeyConstraint(['id_equipment'], ['equipment.id_equipment'], ),
    sa.PrimaryKeyConstraint('id_ch_equipment')
    )
    op.create_table('character_proficiency',
    sa.Column('id_ch_proficiency', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checker', sa.Boolean(), nullable=False),
    sa.Column('id_proficiency', sa.Integer(), nullable=False),
    sa.Column('id_character', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_character'], ['character.id_character'], ),
    sa.ForeignKeyConstraint(['id_proficiency'], ['proficiency.id_proficiency'], ),
    sa.PrimaryKeyConstraint('id_ch_proficiency')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_proficiency')
    op.drop_table('character_equipment')
    op.drop_table('character')
    op.drop_table('user')
    op.drop_table('user_type')
    op.drop_table('racial_group')
    op.drop_table('proficiency')
    op.drop_table('note')
    op.drop_table('equipment')
    op.drop_table('class')
    op.drop_table('attack')
    # ### end Alembic commands ###
